name: TDL Coroutines Test

on:
  push:
    branches:
      - master

jobs:
  test-on-linux-x64:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Run
        run: java -jar tdl-coroutines-example-jvm-all.jar

  test-on-linux-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Run
        run: java -jar tdl-coroutines-example-jvm-all.jar

  test-on-macos-intel:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Run
        run: java -jar tdl-coroutines-example-jvm-all.jar

  test-on-macos-arm64:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Run
        run: java -jar tdl-coroutines-example-jvm-all.jar

  test-on-windows-x64:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin

      - name: Run
        run: java -jar tdl-coroutines-example-jvm-all.jar

  test-on-windows-arm64:
    runs-on: windows-11-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 24
          distribution: temurin
          architecture: aarch64
          check-latest: true

      - name: Run
        run: java -jar tdl-coroutines-example-jvm-all.jar
